### ISSUE TITLE
Please add support for RSA KeyPair rotation

### ISSUE THREAD

**Issue by sql-dr-watson** [hashicorp/vault-plugin-database-snowflake#6]
Currently the provider only does password, can you please help to work a way where we can use RSA Key Pair authentication with Vault and Snowflake?

**Comment by austingebauer** [comment]
Hi, @sql-dr-watson. Thanks for the request. This will be supported in the upcoming Vault 1.11 release via https://github.com/hashicorp/vault-plugin-database-snowflake/pull/15. Closing this issue.
